#pragma once
#include <stdint.h>
#include <stddef.h>

#define SYSCALL_SERIAL_PUTCHAR      1ULL
#define SYSCALL_SERIAL_PUTS         2ULL
#define SYSCALL_SERIAL_WRITE_U64    3ULL
#define SYSCALL_SERIAL_WRITE_U32    4ULL
#define SYSCALL_SERIAL_WRITE_U16    5ULL
#define SYSCALL_PROCESS_CREATE      6ULL
#define SYSCALL_PROCESS_YIELD       7ULL
#define SYSCALL_PROCESS_EXIT        8ULL
#define SYSCALL_THREAD_CREATE       9ULL
#define SYSCALL_FILE_OPEN          23ULL
#define SYSCALL_FILE_READ          24ULL
#define SYSCALL_FILE_WRITE         25ULL
#define SYSCALL_FILE_CLOSE         26ULL
#define SYSCALL_USER_MALLOC       27ULL
#define SYSCALL_USER_FREE         28ULL
#define SYSCALL_USER_MEMCPY        29ULL
#define SYSCALL_USER_MEMCMP        30ULL
#define SYSCALL_USER_MEMSET        31ULL
#define SYSCALL_INPUT_READ_KEYBOARD 32ULL
#define SYSCALL_INPUT_READ_MOUSE    33ULL
#define SYSCALL_FILE_SEEK          34ULL
#define SYSCALL_PROCESS_SPAWN_ELF  36ULL
#define SYSCALL_FILE_MKDIR         37ULL
#define SYSCALL_FILE_OPENDIR       38ULL
#define SYSCALL_FILE_READDIR       39ULL
#define SYSCALL_FILE_CLOSEDIR      40ULL
#define SYSCALL_FILE_UNLINK        41ULL
#define SYSCALL_FILE_CREAT         42ULL
#define SYSCALL_USER_MMAP          43ULL
#define SYSCALL_PROCESS_SIGNAL     44ULL
#define SYSCALL_IPC_SEND_MESSAGE   45ULL
#define SYSCALL_IPC_RECEIVE_MESSAGE 46ULL
#define SYSCALL_PROCESS_GET_PID    47ULL
#define SYSCALL_GET_DISPLAY_WIDTH  48ULL
#define SYSCALL_GET_DISPLAY_HEIGHT 49ULL
#define SYSCALL_WINDOW_REGISTER_SERVICE 50ULL
#define SYSCALL_WINDOW_GET_WM_PID  51ULL
#define SYSCALL_DISPLAY_DRAW_PIXEL 52ULL
#define SYSCALL_DISPLAY_FILL_RECT  53ULL
#define SYSCALL_DISPLAY_PRESENT    54ULL
#define SYSCALL_GET_FAT32_FILE_T   60ULL

#define OS_STATUS_OK             0LL
#define OS_STATUS_NOT_FOUND     -2LL
#define OS_STATUS_IO_ERROR      -5LL
#define OS_STATUS_ACCESS_DENIED -13LL
#define OS_STATUS_FAULT         -14LL
#define OS_STATUS_INVALID_ARG   -22LL
#define OS_STATUS_LIMIT_REACHED -24LL
#define OS_STATUS_NOT_SUPPORTED -95LL
#define OS_STATUS_INTERNAL     -255LL

#ifdef __linux__
#endif
