#pragma once

#ifndef GDT_KERNEL_CODE
#define GDT_KERNEL_CODE      0x08
#endif
#ifndef GDT_KERNEL_DATA
#define GDT_KERNEL_DATA      0x10
#endif
#ifndef GDT_USER_COMPAT_CODE
#define GDT_USER_COMPAT_CODE 0x18
#endif
#ifndef GDT_USER_DATA
#define GDT_USER_DATA        0x20
#endif
#ifndef GDT_USER_CODE
#define GDT_USER_CODE        0x28
#endif
#ifndef GDT_TSS
#define GDT_TSS              0x30
#endif

#ifndef OS_CONFIG_PROCESS_MAX_COUNT
#ifdef PROCESS_MAX_COUNT_CONFIG
#define OS_CONFIG_PROCESS_MAX_COUNT PROCESS_MAX_COUNT_CONFIG
#else
#define OS_CONFIG_PROCESS_MAX_COUNT 64
#endif
#endif

#ifndef OS_CONFIG_FILE_MAX_FD
#ifdef FILE_MAX_FD_CONFIG
#define OS_CONFIG_FILE_MAX_FD FILE_MAX_FD_CONFIG
#else
#define OS_CONFIG_FILE_MAX_FD 32
#endif
#endif

#ifndef OS_CONFIG_FILE_MAX_DIR_HANDLE
#ifdef FILE_MAX_DIR_HANDLE_CONFIG
#define OS_CONFIG_FILE_MAX_DIR_HANDLE FILE_MAX_DIR_HANDLE_CONFIG
#else
#define OS_CONFIG_FILE_MAX_DIR_HANDLE 32
#endif
#endif

#ifndef PROCESS_MAX_COUNT_CONFIG
#define PROCESS_MAX_COUNT_CONFIG OS_CONFIG_PROCESS_MAX_COUNT
#endif

#ifndef FILE_MAX_FD_CONFIG
#define FILE_MAX_FD_CONFIG OS_CONFIG_FILE_MAX_FD
#endif

#ifndef FILE_MAX_DIR_HANDLE_CONFIG
#define FILE_MAX_DIR_HANDLE_CONFIG OS_CONFIG_FILE_MAX_DIR_HANDLE
#endif

#define OS_CONFIG_PROCESS_MAX_COUNT_MIN   1
#define OS_CONFIG_PROCESS_MAX_COUNT_MAX   256
#define OS_CONFIG_FILE_MAX_FD_MIN         4
#define OS_CONFIG_FILE_MAX_FD_MAX         256
#define OS_CONFIG_FILE_MAX_DIR_HANDLE_MIN 4
#define OS_CONFIG_FILE_MAX_DIR_HANDLE_MAX 256

#if (PROCESS_MAX_COUNT_CONFIG < OS_CONFIG_PROCESS_MAX_COUNT_MIN) || \
    (PROCESS_MAX_COUNT_CONFIG > OS_CONFIG_PROCESS_MAX_COUNT_MAX)
#error "PROCESS_MAX_COUNT_CONFIG is out of supported range"
#endif

#if (FILE_MAX_FD_CONFIG < OS_CONFIG_FILE_MAX_FD_MIN) || \
    (FILE_MAX_FD_CONFIG > OS_CONFIG_FILE_MAX_FD_MAX)
#error "FILE_MAX_FD_CONFIG is out of supported range"
#endif

#if (FILE_MAX_DIR_HANDLE_CONFIG < OS_CONFIG_FILE_MAX_DIR_HANDLE_MIN) || \
    (FILE_MAX_DIR_HANDLE_CONFIG > OS_CONFIG_FILE_MAX_DIR_HANDLE_MAX)
#error "FILE_MAX_DIR_HANDLE_CONFIG is out of supported range"
#endif

#if FILE_MAX_DIR_HANDLE_CONFIG > FILE_MAX_FD_CONFIG
#error "FILE_MAX_DIR_HANDLE_CONFIG must be <= FILE_MAX_FD_CONFIG"
#endif

#ifndef OS_CONFIG_SMP_MAX_CPUS
#define OS_CONFIG_SMP_MAX_CPUS 2
#endif

#ifndef OS_CONFIG_SMP_ENABLED
#define OS_CONFIG_SMP_ENABLED 1
#endif

#ifndef OS_CONFIG_LOG_FILE_MAX_BYTES
#define OS_CONFIG_LOG_FILE_MAX_BYTES (512 * 1024)
#endif

#ifndef OS_CONFIG_SIGNAL_HANDLER_MAX_PER_PROCESS
#define OS_CONFIG_SIGNAL_HANDLER_MAX_PER_PROCESS 32
#endif

#ifndef OS_CONFIG_PENDING_SIGNAL_MAX_PER_PROCESS
#define OS_CONFIG_PENDING_SIGNAL_MAX_PER_PROCESS 32
#endif

#ifndef OS_CONFIG_NET_IPV4_ADDR
#define OS_CONFIG_NET_IPV4_ADDR 0x0A00020FULL
#endif

#ifndef OS_CONFIG_NET_IPV4_MASK
#define OS_CONFIG_NET_IPV4_MASK 0xFFFFFF00ULL
#endif

#ifndef OS_CONFIG_NET_IPV4_GATEWAY
#define OS_CONFIG_NET_IPV4_GATEWAY 0x0A000202ULL
#endif
