#pragma once
#include <stdint.h>
#include <stddef.h>

#define SYSCALL_SERIAL_PUTCHAR      1ULL
#define SYSCALL_SERIAL_PUTS         2ULL
#define SYSCALL_SERIAL_WRITE_U64    3ULL
#define SYSCALL_SERIAL_WRITE_U32    4ULL
#define SYSCALL_SERIAL_WRITE_U16    5ULL
#define SYSCALL_PROCESS_CREATE      6ULL
#define SYSCALL_PROCESS_YIELD       7ULL
#define SYSCALL_PROCESS_EXIT        8ULL
#define SYSCALL_THREAD_CREATE       9ULL
#define SYSCALL_THREAD_EXIT        10ULL
#define SYSCALL_THREAD_JOIN        11ULL
#define SYSCALL_THREAD_DETACH      12ULL
#define SYSCALL_FILE_OPEN          23ULL
#define SYSCALL_FILE_READ          24ULL
#define SYSCALL_FILE_WRITE         25ULL
#define SYSCALL_FILE_CLOSE         26ULL
#define SYSCALL_USER_MALLOC       27ULL
#define SYSCALL_USER_FREE         28ULL
#define SYSCALL_USER_MEMCPY        29ULL
#define SYSCALL_USER_MEMCMP        30ULL
#define SYSCALL_USER_MEMSET        31ULL
#define SYSCALL_INPUT_READ_KEYBOARD 32ULL
#define SYSCALL_INPUT_READ_MOUSE    33ULL
#define SYSCALL_FILE_SEEK          34ULL
#define SYSCALL_PROCESS_SPAWN_ELF  36ULL
#define SYSCALL_FILE_MKDIR         37ULL
#define SYSCALL_FILE_OPENDIR       38ULL
#define SYSCALL_FILE_READDIR       39ULL
#define SYSCALL_FILE_CLOSEDIR      40ULL
#define SYSCALL_FILE_UNLINK        41ULL
#define SYSCALL_FILE_CREAT         42ULL
#define SYSCALL_USER_MMAP          43ULL
#define SYSCALL_PROCESS_SIGNAL     44ULL
#define SYSCALL_IPC_SEND_MESSAGE   45ULL
#define SYSCALL_IPC_RECEIVE_MESSAGE 46ULL
#define SYSCALL_PROCESS_GET_PID    47ULL
#define SYSCALL_GET_DISPLAY_WIDTH  48ULL
#define SYSCALL_GET_DISPLAY_HEIGHT 49ULL
#define SYSCALL_WINDOW_REGISTER_SERVICE 50ULL
#define SYSCALL_WINDOW_GET_WM_PID  51ULL
#define SYSCALL_DISPLAY_DRAW_PIXEL 52ULL
#define SYSCALL_DISPLAY_FILL_RECT  53ULL
#define SYSCALL_DISPLAY_PRESENT    54ULL
#define SYSCALL_GET_DISPLAY_FRAMEBUFFER 55ULL
#define SYSCALL_DISPLAY_GET_PIXEL  56ULL
#define SYSCALL_DISPLAY_GET_TOPOLOGY 57ULL
#define SYSCALL_DISPLAY_GET_MONITOR_INFO 58ULL
#define SYSCALL_DISPLAY_GET_MONITOR_MODE_INFO 59ULL
#define SYSCALL_DISPLAY_SET_MONITOR_MODE 60ULL
#define SYSCALL_DISPLAY_PRESENT_RECTS 61ULL
#define SYSCALL_WINDOW_GET_POINTER_STATE 62ULL

#define SYSCALL_UDP_SEND          100ULL
#define SYSCALL_TCP_CONNECT       101ULL
#define SYSCALL_TCP_LISTEN        102ULL
#define SYSCALL_TCP_ACCEPT        103ULL
#define SYSCALL_TCP_SEND          104ULL
#define SYSCALL_TCP_RECV          105ULL
#define SYSCALL_TCP_CLOSE         106ULL
#define SYSCALL_TCP_GET_STATE     107ULL
#define SYSCALL_UDP_BIND          108ULL
#define SYSCALL_UDP_UNBIND        109ULL
#define SYSCALL_PROCESS_WAITPID   110ULL
#define SYSCALL_PROCESS_GETPPID   111ULL
#define SYSCALL_PROCESS_EXIT_STATUS 112ULL
#define SYSCALL_SLEEP             113ULL
#define SYSCALL_FILE_STAT         114ULL
#define SYSCALL_FILE_PIPE         115ULL
#define SYSCALL_FILE_DUP          116ULL
#define SYSCALL_FILE_DUP2         117ULL
#define SYSCALL_GETCWD            118ULL
#define SYSCALL_GET_UPTIME_MS     119ULL
#define SYSCALL_NANOSLEEP         120ULL
#define SYSCALL_GET_PROC_COUNT    121ULL
#define SYSCALL_GET_PROC_INFO     122ULL
#define SYSCALL_PROCESS_SPAWN_ELF_ARG 123ULL
#define SYSCALL_PROCESS_GET_LAUNCH_ARG 124ULL
#define SYSCALL_GET_PROC_PERF_INFO 125ULL
#define SYSCALL_GET_BOOT_PROFILE_COUNT 126ULL
#define SYSCALL_GET_BOOT_PROFILE_ENTRY 127ULL

#define SYSCALL_SOCKET_CREATE     130ULL
#define SYSCALL_SOCKET_CONNECT    131ULL
#define SYSCALL_SOCKET_BIND       132ULL
#define SYSCALL_SOCKET_LISTEN     133ULL
#define SYSCALL_SOCKET_ACCEPT     134ULL
#define SYSCALL_SOCKET_SEND       135ULL
#define SYSCALL_SOCKET_RECV       136ULL
#define SYSCALL_SOCKET_CLOSE      137ULL
#define SYSCALL_SOCKET_GET_INFO   141ULL
#define SYSCALL_SOCKET_SET_OPTION 142ULL
#define SYSCALL_SOCKET_GET_OPTION 143ULL
#define SYSCALL_SOCKET_SHUTDOWN   144ULL
#define SYSCALL_SOCKET_LISTEN_EX  145ULL
#define SYSCALL_UDP_RECV          138ULL
#define SYSCALL_GET_RTC_TIME      140ULL

#define SYSCALL_MPROTECT          150ULL
#define SYSCALL_MUNMAP            151ULL
#define SYSCALL_MREMAP            152ULL
#define SYSCALL_GETTID            158ULL
#define SYSCALL_SET_TID_ADDRESS   159ULL
#define SYSCALL_GETRANDOM         170ULL
#define SYSCALL_RENAME            175ULL
#define SYSCALL_FD_POLL           179ULL
#define SYSCALL_FUTEX             180ULL
#define SYSCALL_CLONE             181ULL
#define SYSCALL_TKILL             186ULL
#define SYSCALL_SHM_CREATE        187ULL
#define SYSCALL_SHM_GRANT         188ULL
#define SYSCALL_SHM_MAP           189ULL
#define SYSCALL_FORK              190ULL
#define SYSCALL_EXECVE            191ULL
#define SYSCALL_VFORK             192ULL
#define SYSCALL_SET_ROBUST_LIST   193ULL
#define SYSCALL_SHM_UNMAP         194ULL
#define SYSCALL_SHM_CLOSE         195ULL
#define SYSCALL_GET_MAIN_IMAGE_INFO 196ULL

#define SYSCALL_AUDIO_OPEN        230ULL
#define SYSCALL_AUDIO_GET_INFO    231ULL
#define SYSCALL_AUDIO_WRITE       232ULL
#define SYSCALL_AUDIO_DRAIN       233ULL
#define SYSCALL_AUDIO_CLOSE       234ULL

#define SYSCALL_SYSTEM_SHUTDOWN   250ULL
#define SYSCALL_SYSTEM_REBOOT     251ULL
#define SYSCALL_SYSTEM_SHUTDOWN_BROADCAST 252ULL
#define SYSCALL_GET_TOTAL_MEMORY  253ULL
#define SYSCALL_GET_USED_MEMORY   254ULL

#define SYSCALL_GET_PROC_DEBUG_INFO  260ULL
#define SYSCALL_GET_OS_DEBUG_INFO    261ULL

#define SYSCALL_WIFI_SCAN_START        262ULL
#define SYSCALL_WIFI_GET_SCAN_RESULTS  263ULL
#define SYSCALL_WIFI_CONNECT           264ULL
#define SYSCALL_WIFI_DISCONNECT        265ULL
#define SYSCALL_WIFI_GET_STATUS        266ULL
#define SYSCALL_NET_GET_DHCP_DNS       267ULL

#define OS_STATUS_OK             0LL
#define OS_STATUS_NOT_FOUND     -2LL
#define OS_STATUS_IO_ERROR      -5LL
#define OS_STATUS_ACCESS_DENIED -13LL
#define OS_STATUS_FAULT         -14LL
#define OS_STATUS_INVALID_ARG   -22LL
#define OS_STATUS_LIMIT_REACHED -24LL
#define OS_STATUS_NOT_SUPPORTED -95LL
#define OS_STATUS_INTERNAL     -255LL

#ifdef __linux__
#endif
