macro(implusos_curl_cache name value)
  set(${name} ${value} CACHE INTERNAL "ImplusOS libcurl prefill" FORCE)
endmacro()

macro(implusos_curl_type_size name value)
  implusos_curl_cache(HAVE_SIZEOF_${name} TRUE)
  implusos_curl_cache(SIZEOF_${name} ${value})
  implusos_curl_cache(SIZEOF_${name}_CODE "#define SIZEOF_${name} ${value}")
endmacro()

implusos_curl_cache(HAVE_ARPA_INET_H 1)
implusos_curl_cache(HAVE_DIRENT_H 1)
implusos_curl_cache(HAVE_FCNTL_H 1)
implusos_curl_cache(HAVE_IFADDRS_H 1)
implusos_curl_cache(HAVE_LOCALE_H 1)
implusos_curl_cache(HAVE_NETDB_H 1)
implusos_curl_cache(HAVE_NETINET_IN_H 1)
implusos_curl_cache(HAVE_POLL_H 1)
implusos_curl_cache(HAVE_STDBOOL_H 1)
implusos_curl_cache(HAVE_STDDEF_H 1)
implusos_curl_cache(HAVE_STDINT_H 1)
implusos_curl_cache(HAVE_STRINGS_H 1)
implusos_curl_cache(HAVE_SYS_SELECT_H 1)
implusos_curl_cache(HAVE_SYS_SOCKET_H 1)
implusos_curl_cache(HAVE_SYS_TIME_H 1)
implusos_curl_cache(HAVE_SYS_TYPES_H 1)
implusos_curl_cache(HAVE_UNISTD_H 1)
implusos_curl_cache(STDC_HEADERS 1)

implusos_curl_cache(HAVE_BOOL_T 1)
implusos_curl_cache(HAVE_CLOCK_GETTIME_MONOTONIC 1)
implusos_curl_cache(HAVE_CLOSESOCKET 1)
implusos_curl_cache(HAVE_FCNTL 1)
implusos_curl_cache(HAVE_FCNTL_O_NONBLOCK 1)
implusos_curl_cache(HAVE_FREEADDRINFO 1)
implusos_curl_cache(HAVE_GETADDRINFO 1)
implusos_curl_cache(HAVE_GETADDRINFO_THREADSAFE 1)
implusos_curl_cache(HAVE_GETPEERNAME 1)
implusos_curl_cache(HAVE_GETSOCKNAME 1)
implusos_curl_cache(HAVE_GETTIMEOFDAY 1)
implusos_curl_cache(HAVE_GMTIME_R 1)
implusos_curl_cache(HAVE_INET_NTOP 1)
implusos_curl_cache(HAVE_INET_PTON 1)
implusos_curl_cache(HAVE_LOCALTIME_R 1)
implusos_curl_cache(HAVE_POLL 1)
implusos_curl_cache(HAVE_RECV 1)
implusos_curl_cache(HAVE_SA_FAMILY_T 1)
implusos_curl_cache(HAVE_SELECT 1)
implusos_curl_cache(HAVE_SEND 1)
implusos_curl_cache(HAVE_SOCKET 1)
implusos_curl_cache(HAVE_STRCASECMP 1)
implusos_curl_cache(HAVE_STRUCT_SOCKADDR_STORAGE 1)
implusos_curl_cache(HAVE_STRUCT_TIMEVAL 1)
implusos_curl_cache(HAVE_SUSECONDS_T 1)

implusos_curl_type_size(INT 4)
implusos_curl_type_size(LONG 8)
implusos_curl_type_size(OFF_T 8)
implusos_curl_type_size(CURL_OFF_T 8)
implusos_curl_type_size(CURL_SOCKET_T 4)
implusos_curl_type_size(SIZE_T 8)
implusos_curl_type_size(SSIZE_T 8)
implusos_curl_type_size(SUSECONDS_T 8)
implusos_curl_type_size(TIME_T 8)
implusos_curl_type_size(SA_FAMILY_T 2)
implusos_curl_type_size(STRUCT_SOCKADDR_STORAGE 128)
